### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by loxy** [krakenjs/post-robot#31] opened 2017-07-04 10:06 UTC
Are there any typings (TypeScript) or plans to provide them? Can't find anything on that topic...

**Comment by bluepnume** [comment] 2017-07-05 19:57
We use flow typings in the source code, but right now these aren't externalized in any way. May be a gulp task or something to turn the source-code annotations into a flow/typescript typings file that can be published with /dist. If you want to take a look at adding this, please feel free.

**Comment by loxy** [comment] 2017-07-05 20:34
I will have a look...

**Comment by loxy** [comment] 2017-07-26 11:16
Should the typings published under DefinitelyTyped or be part of this repo?

**Comment by haskasu** [comment] 2017-08-31 08:42
It would be really nice if there is typings .

**Comment by mbenzenhoefer** [comment] 2018-02-19 10:49
+1

**Comment by jducobu** [comment] 2018-03-21 14:39
+1

**Comment by NinoScript** [comment] 2018-07-17 22:36
I'm not planning on making this correct or extensive, nor am I thinking about publishing it under DefinitelyTyped for now, but I'm using this in my project:

https://gist.github.com/NinoScript/6478d60282816393ca75c99937a9f6e5

It may be better than nothing, or at least a starting point.

**Comment by songz** [comment] 2020-10-09 00:28
should we close this because its a dupe of #89 ?

**Closed** 2020-10-13 16:28 UTC
